### PR TITLE
Handle missing permissions

### LINKED ISSUE #43: Handle missing permission
**Describe the bug**
Currently, the bot returns an unhandled promise rejection if it doesn't have permission to write in a channel.

**To Reproduce**
1. Add the bot to a server
2. Remove the writing permission on a channel for the bot
3. Send the bot a command (e.g. `!sub d2`)
4. The bot will return an unhandled promise rejection

**Expected behavior**
The bot should handle the rejected promise or not try to write in the channel at all. If the channel is subscribed to the bot it should unsubscribe itself, to prevent errors in the future.

### PR DESCRIPTION
**Pull request by TimJentzsch**
**Description**:
Handles being missing permissions or access:
- Remove channel data when being removed from a channel (except from a Telegram channel group, not handled by their events)
- Check for writing permissions before sending messages, subscribing and changing the prefix
- Clean up dead channels on startup and before using the `stats` command

Also fixes some issues with async commands and their time measurements.
Closes #43.

**Checklist**:

- [x] Tested the bot on both clients with a few commands
- [x] Updated the [`README`](README.md) if necessary
- [x] Updated the version string in the [`package.json`](package.json) if necessary

### CODE REVIEW

File: src/user.ts [hunk 1]
```diff
@@ -17,38 +17,38 @@ export default class User {
     this.bot = bot;
     this.id = id;
   }
-  /** Get's the user's permission on the given channel.
+  /** Get's the user's rpöe on the given channel.
```
Comment (zachkont) [inline src/user.ts]: rpoe? :P

File: src/notifications/notification.ts [hunk 2]
```diff
@@ -137,19 +138,27 @@ export default class Notification implements Comparable<Notification> {
...
       const authorText = this.author.link
         ? `[${this.author.text}](${this.author.link})`
         : this.author.text;
 
-      return `New **${this.game.label}** update - ${authorText}:\n\n${titleText}\n\n${this.content}`;
+      const contentText = this.content ? `\n\n${this.content}` : '';
+      mdStr = `New **${this.game.label}** update - ${authorText}:\n\n${titleText}${contentText}`;
+    } else {
+      const contentText = this.content ? `\n\n${this.content}` : '';
+      mdStr = `New **${this.game.label}** update:\n\n${titleText}${contentText}`;
```
Comment (zachkont) [inline src/notifications/notification.ts]: you can just set up the author text including the dash inside the if and use it anyway, similar to the content

File: src/user.ts (hunk 1 above)
Comment (TimJentzsch) [reply src/user.ts]: Fixed.
