### PR TITLE
#289 Limit Discord embed titles if they exceed the maximum length

### LINKED ISSUE #289: Fix Discord updates failing with long title
**Description:**
Updates with a long title fail with the following error:
```
DiscordAPIError: Invalid Form Body
embed.title: Must be 256 or fewer in length.
```

**Expected behavior:**
The notification title should be limited to 256 characters when being converted to an embed. This should only affect the title text, not the formatting of the title.

### PR DESCRIPTION
**Pull request by TimJentzsch**
**Description**:
- Limit Discord embed titles if they exceed the maximum length

Closes #289.

**Checklist**:

- [x] Tested the bot on both clients with a few commands
- [x] Updated the [`README`](README.md) if necessary
- [x] Updated the version string in the [`package.json`](package.json) if necessary

### CODE REVIEW

File: src/util/util.ts [hunk 1]
```diff
@@ -110,7 +110,7 @@ export class StrUtil {
    * @param indicator - The indicator to use when the string is too long.
    */
   public static naturalLimit(str: string, limit: number, indicator?: string): string {
-    const newIndicator = indicator == null ? '...' : indicator;
+    const newIndicator = indicator ?? '...';
```
Comment (zachkont) [inline src/util/util.ts:113]: this can be a default value in the parameter right?

Comment (TimJentzsch) [reply src/util/util.ts]: Fixed

**Review by zachkont — APPROVED** [review]
