### PR TITLE
#239 Refactor updater

### LINKED ISSUE #188: Fix reddit API rate limit handling
**Describe the bug**
Currently, when the reddit API rate limit gets exceeded, a lot of errors are thrown.

**Expected behavior**
The reddit providers should wait for the next rate limit refresh and delay the updater if necessary.

### LINKED ISSUE #239: Split up update cycles per provider
**Description:**
Instead of updating all providers of all games at the same time, each provider should have an independant update cycle. This way, we can throttle each provider according to their API guidelines.

### PR DESCRIPTION
**Pull request by TimJentzsch**
**Description**:
Separates the updater in one updater per provider. This enables us to throttle the updaters independently, depending on the status of their source.
Closes #188, #239, #240.

**WIP, still to do:**
- [x] Adjust `InitManager` to handle the new updater data and config format
- [x] Adjust updater limits, since every source has it's own limit now

**Checklist**:

- [x] Tested the bot on both clients with a few commands
- [x] Updated the [`README`](README.md) if necessary
- [x] Updated the version string in the [`package.json`](package.json) if necessary

### CODE REVIEW

File: src/game.ts [hunk 1]
```diff
@@ -1,11 +1,16 @@
...
-import RedditProvider from './providers/reddit_provider';
+import SubredditProvider from './providers/subreddit_provider';
 import RedditUserProvider from './reddit/reddit_user';
 import DotaProvider from './providers/dota_provider';
 import TelegramIVTemplate from './telegram_iv_template';
 import SteamProvider from './providers/steam_provider';
+import RedditProvider from './providers/reddit_provider';
+
+export type Providers = {
+  [index: string]: Provider;
```
Comment (zachkont) [inline src/game.ts:12]: this can be `keyof updater_config` instead of any string

File: src/_main.ts [hunk 2]
```diff
@@ -62,12 +62,16 @@ export default class Main {
...
-      Updater.logger.info('Started updater.');
-    }
+  /** Starts the updaters. */
+  public static async startUpdaters(): Promise<void> {
+    const updaters = Updater.getUpdaters();
+
+    updaters.forEach((updater) => {
+      if (updater.enabled) {
+        updater.start();
+        updater.logger.info('Started updater.');
```
Comment (zachkont) [inline src/_main.ts:72]: This would just log `started updater` multiple times right? Can we log which updater started?

File: src/providers/reddit_provider.ts [hunk 3]
```diff
@@ -1,45 +1,29 @@
...
 
-    // Combine the user notifications
-    let notifications = mergeArrays(userNotifications);
-    // Limit the length
+    // Merge the results
+    let notifications = mergeArrays(subredditNotifications);
     notifications = sortLimitEnd(notifications, limit);
 
+    // Merge the results
     return notifications;
```
Comment (zachkont) [inline src/providers/reddit_provider.ts:27]: This can be
```ts
return sortLimitEnd(mergeArrays(subredditNotifications), limit);
```

but if you prefer it more spread out at least remove the duplicate `// Merge the results` comment

File: src/reddit/reddit_post.ts [hunk 4]
```diff
@@ -103,12 +107,20 @@ export default class RedditPost {
...
+
     return titleFilter.test(this.title);
   }
 
   /** Checks if the submission is new. */
-  public isNew(date: Date): boolean {
+  public isNew(date?: Date): boolean {
+    if (!date) {
+      return true;
+    }
```
Comment (zachkont) [inline src/reddit/reddit_post.ts:122]: So when the submission doesn't have a date it's always considered to be new?

File: src/steam/steam_web_api.ts [hunk 5]
```diff
@@ -10,7 +10,7 @@ export default class SteamWebAPI {
   public static logger = new Logger('SteamWebAPI');
   public static instance = axios.create({
     baseURL: 'https://api.steampowered.com/',
-    timeout: 1000,
+    timeout: 5000,
```
Comment (zachkont) [inline src/steam/steam_web_api.ts:13]: Let's make this an uppercase const at the top of the file to make it more noticeable

Comment (zachkont) [reply src/steam/steam_web_api.ts:13]: could even be a config parameter with a default value of 5000

File: src/_main.ts (hunk 2 above)
Comment (TimJentzsch) [reply src/_main.ts:72]: It does with the updater label. It looks like this: 
```
[1] 2020-09-02 10:05:27 [Updater (reddit)]       info:   Started updater.
[1] 2020-09-02 10:05:27 [Updater (steam)]        info:   Started updater.
[1] 2020-09-02 10:05:27 [Updater (rss)]  info:   Started updater.
[1] 2020-09-02 10:05:27 [Updater (dota)]         info:   Started updater.
```

File: src/providers/reddit_provider.ts (hunk 3 above)
Comment (TimJentzsch) [reply src/providers/reddit_provider.ts:27]: Fixed

File: src/reddit/reddit_post.ts (hunk 4 above)
Comment (TimJentzsch) [reply src/reddit/reddit_post.ts:122]: Yes, hmm I guess we need to find a better solution

File: src/steam/steam_web_api.ts (hunk 5 above)
Comment (TimJentzsch) [reply src/steam/steam_web_api.ts:13]: I choose the const for now, maybe we can change it to config later

File: src/game.ts (hunk 1 above)
Comment (TimJentzsch) [reply src/game.ts:12]: I moved this to #295.

File: src/reddit/reddit_post.ts (hunk 4 above)
Comment (TimJentzsch) [reply src/reddit/reddit_post.ts:122]: Nvm, this is not the submission date, but the filter date, so this should be correct.

**Review by zachkont — APPROVED** [review]
